name: Publish NuGet Packages

on:
  push:
    branches: [ main ]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x

    - name: Restore dependencies
      run: dotnet restore src/Extend.NET.sln

    - name: Build
      run: dotnet build src/Extend.NET.sln --configuration Release --no-restore

    - name: Test
      run: dotnet test src/Extend.NET.sln --no-restore --verbosity normal

    - name: Pack
      run: |
        dotnet pack src/Extend.NET.File/Extend.NET.File.csproj --configuration Release --no-build --output nupkgs
        dotnet pack src/Extend.NET.String/Extend.NET.String.csproj --configuration Release --no-build --output nupkgs
        dotnet pack src/Extend.NET.NLP/Extend.NET.NLP.csproj --configuration Release --no-build --output nupkgs
        dotnet pack src/Extend.NET.Math/Extend.NET.Math.csproj --configuration Release --no-build --output nupkgs
        dotnet pack src/Extend.NET.DateTime/Extend.NET.DateTime.csproj --configuration Release --no-build --output nupkgs
        dotnet pack src/Extend.NET.Dictionary/Extend.NET.Dictionary.csproj --configuration Release --no-build --output nupkgs
        dotnet pack src/Extend.NET.Enum/Extend.NET.Enum.csproj --configuration Release --no-build --output nupkgs
        dotnet pack src/Extend.NET.Regex/Extend.NET.Regex.csproj --configuration Release --no-build --output nupkgs
  


    - name: Publish to NuGet
      run: |
        for f in ./nupkgs/*.nupkg
        do
          dotnet nuget push $f --api-key ${{secrets.NUGET_API_KEY}} --source https://api.nuget.org/v3/index.json --skip-duplicate
        done
      env:
        NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}

    - name: Publish symbols to NuGet
      run: |
        for f in ./nupkgs/*.snupkg
        do
          dotnet nuget push $f --api-key ${{secrets.NUGET_API_KEY}} --source https://api.nuget.org/v3/index.json --skip-duplicate
        done
      env:
        NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}